version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network

  kafka-ui:
    image: landoop/fast-data-dev:latest
    container_name: kafka-ui
    ports:
      - "3030:3030"
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

